### ISSUE TITLE
vignette order

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#15]
it's really helpful if vignettes are ordered in a meaningful way (easiest, introductions first, etc) on this page:

http://code.databio.org/pepr/articles/index.html

Follow this example:
https://github.com/nsheff/LOLA/blob/master/_pkgdown.yaml

adding something like this to `_pkgdown.yaml`
```
articles:
  - title: Vignettes
    contents:
      - gettingStarted
      - usingLOLACore
      - choosingUniverse
```
