### ISSUE TITLE
dictionary with empty value in YAML

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/pepr#22]
A YAML file with an empty value for a key produces the following error:
```R
Error in x[[jj]][iseq] <- vjj : replacement has length zero
```

This is handled without error or warning outside of R. Replacing empty value with null does not resolve issue.

Example file:
```yaml
# Run gold standard samples through ATACseq pipeline.
name: gold5_wo_00

metadata:
  sample_annotation: "$DATA/meta/gold5_annotation.csv"
  output_dir: "$PROCESSED/gold/pepatac/gold5/hg19/wo_pre/samblaster/00"
  pipeline_interfaces: "$CODE/pepatac/pipeline_interface.yaml" 
  
derived_columns: [read1, read2]

data_sources:
  SRA_1: "${SRAFQ}/{SRR}_1.fastq.gz"
  SRA_2: "${SRAFQ}/{SRR}_2.fastq.gz"
  
implied_columns:
  organism:
    human:
      genome: hg19
      macs_genome_size: hs
      prealignments:
```
