### ISSUE TITLE
derived columns are saved as character vectors, but appended columns are saved as lists

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#44]
I think these should be consistent.

project config:
```
pep_version: 2.0.0
sample_table: "sample_table_demo.csv"
sample_modifiers:
  append:
    path1: "$CODE/path1"
  derive:
    attributes: path2
    sources:
      FILE: "$CODE/path2"
```

sample_table_demo.csv:
```
sample_name,path2
sample1,FILE
sample2,FILE
sample3,FILE
```

Inconsistent processing:

```
p = pepr::Project("project_config_demo.yaml")
st = pepr::sampleTable(p)> st = pepr::sampleTable(p)
> st
   sample_name                   path2                   path1
1:     sample1 /home/nsheff/code/path2 /home/nsheff/code/path1
2:     sample2 /home/nsheff/code/path2 /home/nsheff/code/path1
3:     sample3 /home/nsheff/code/path2 /home/nsheff/code/path1
> st$path2
[1] "/home/nsheff/code/path2" "/home/nsheff/code/path2"
[3] "/home/nsheff/code/path2"
> st$path1
[[1]]
[1] "/home/nsheff/code/path1"

[[2]]
[1] "/home/nsheff/code/path1"

[[3]]
[1] "/home/nsheff/code/path1"
> class(st$path1)
[1] "list"
> class(st$path2)
[1] "character"
```
