### ISSUE TITLE
Improve error for bad derived attribute

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#45]
give a missing attribute as a derived attribute and you get this:

```
pep_version: 2.0.0
sample_table: "sample_table_demo.csv"
sample_modifiers:
  append:
    path1: "$CODE/path1"
  derive:
    attributes: NON_EXISTANT_ATTRIBUTE
    sources:
      FILE: "$CODE/path2"
```

> p = pepr::Project("project_config_demo.yaml")
Loading config file: /home/nsheff/code/bedshift_analysis/pep_universe/project_config_demo.yaml
Error in `[.data.frame`(x, i, j) : undefined columns selected
